# Generated by Django 4.0.5 on 2022-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('brand', models.CharField(max_length=254)),
                ('colour', models.CharField(max_length=254)),
                ('paint_type', models.CharField(choices=[('OL', 'Oil'), ('AC', 'Acrylic'), ('WC', 'Watercolor'), ('GC', 'Gouache'), ('PS', 'Pastel'), ('EC', 'Encaustic')], max_length=2)),
                ('size', models.CharField(choices=[(1, '8ml'), (2, '15ml'), (3, '30ml'), (4, '50ml'), (5, '75ml')], max_length=2)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory_count', models.IntegerField(default=0)),
            ],
        ),
    ]
