# Generated by Django 4.0.5 on 2022-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(1, '8ml'), (2, '15ml'), (3, '30ml'), (4, '50ml'), (5, '75ml')], max_length=2),
        ),
    ]
